### ISSUE TITLE
PS2 game detection

### ISSUE THREAD

**Issue by WebbedMite11401** [zorua98741/PS3-Rich-Presence-for-Discord#1]
PS2 games don't seem to be detected at all as webman can't be found after launching one, this happens on cfw but probably happens on hen as well.

**Comment by zorua98741** [comment]
Hello, thank you for reporting the issue.
I've been aware of this for a while, and unfortunately there is no way to fix this issue, as webman does not run while in PS2 mode.
Once i find some time, there may be a way for me to make PS2 games display more consistently, but no matter the method, it will be hacky at best.
Currently, PS3RPD will display a PS2 game in the presence if it is mounted (but not opened) and the program "refreshes" itself, which currently happens every 35 seconds, (the planned change will see this refresh time down to ~15 seconds)
