### ISSUE TITLE
PS3 Rich Presence Rewrite

### ISSUE THREAD

**Issue by AndreCox** [zorua98741/PS3-Rich-Presence-for-Discord#10]
Hey [zorua98741](https://github.com/zorua98741) I think this script is awesome however I wanted slightly more performance so I rewrote it in Rust. I also changed the way images are handled as we can fetch them from an online database of ps3 games which means there's no need for a sqlite database. Hopefully you can get some use for your own script.

https://github.com/AndreCox/PS3-Rich-Presence-for-Discord-Rusty

Thanks :)

**Comment by zorua98741** [comment]
Well done! 
I like your use of gametdb to resolve titleIDs to images, it would be great to remove the need for a database file on the users PC. 
The main thought process behind using it was to allow users to change images as they please, so I might look into having both gametdb and the sqlite database used :)
