### ISSUE TITLE
use_Gametdb: Unexpected key: i

### ISSUE THREAD

**Issue by Jump-Suit** [zorua98741/PS3-Rich-Presence-for-Discord#11]
This bug happens when booting PlayStation Home with titleId `NPIA00010` or `NPIA00005` with `I` in the NP`I`A presumably throwing the unexpected key error? 
![image](https://github.com/zorua98741/PS3-Rich-Presence-for-Discord/assets/26616362/5330f8ce-5913-4c3a-85e9-004787eb4890)

**Comment by Jump-Suit** [comment]
Judging by the python code, and the readme, I presume this titleId just doesn't exist on the discord dev app dashboard for Rich Presence?

**Comment by zorua98741** [comment]
Hello, thank you for submitting a bug report.
You guessed correctly, the titleID doesn't have an entry on GameTDB, or on my Discord developer application, if you would like me to upload an image for a game, please link/send me the image and the corresponding titleID it belongs to

**Comment by Jump-Suit** [comment]
Will just the Icons work for this? 
![ICON0](https://github.com/zorua98741/PS3-Rich-Presence-for-Discord/assets/26616362/f6381ff0-0988-421b-a954-1bc6b38263c4)
![ICON0_00](https://github.com/zorua98741/PS3-Rich-Presence-for-Discord/assets/26616362/e0f82ade-c973-4182-b9dc-45a7ffad6f9d)
This can apply for `NPIA00010`, `NPIA00005`, and `NPEA00013` for PlayStation Home.

**Comment by zorua98741** [comment]
Thank you, I've uploaded the icons and they should be working with the script within the next 10 minutes
