### ISSUE TITLE
how do i quit the rich presence once the program does not detect the ps3?

### ISSUE THREAD

**Issue by lbupqdPQEW8PTO** [zorua98741/PS3-Rich-Presence-for-Discord#15]
i put the program as a nssm service but when i turn off my ps3 the rich presence stays there, i wonder if this could be changed to deactivate the rich presence automatically when the program doesn't detect the console and viceversa

**Comment by lbupqdPQEW8PTO** [comment]
i put the program as a nssm service but when i turn off my ps3 the rich presence stays there, i wonder if this could be changed to deactivate the rich presence automatically when the program doesn't detect the console

**Comment by zorua98741** [comment]
Please try the latest release

**Comment by lbupqdPQEW8PTO** [comment]
> Please try the latest release

now it stays like this: 
![image](https://github.com/zorua98741/PS3-Rich-Presence-for-Discord/assets/88113801/3ec1c563-27f1-4663-bd52-e2e0bcbc6c65)

**Comment by lbupqdPQEW8PTO** [comment]
now the problem is that the time elapsed does not reset once the rich presence hibernates.

**Comment by lbupqdPQEW8PTO** [comment]
i even turned off my pc and when i turned it on the activity started counting from 3h eta lol

**Comment by lbupqdPQEW8PTO** [comment]
![image](https://github.com/zorua98741/PS3-Rich-Presence-for-Discord/assets/88113801/373d14e8-a94c-41db-904d-6b9530208d62)

**Comment by zorua98741** [comment]
That should(?) be fixed now

**Comment by lbupqdPQEW8PTO** [comment]
Well, my issues are resolved, thankyou so much :D
