### ISSUE TITLE
Program crashes

### ISSUE THREAD

**Issue by BeemerDream** [zorua98741/PS3-Rich-Presence-for-Discord#21]
When I'm starting the program a window opens and then closes immediately. I'm on Windows 11.

**Comment by zorua98741** [comment]
please open a command prompt window in the same directory as the script and run the script through command prompt so that any output from the script can be captured

**Comment by BeemerDream** [comment]
I'll try that. Thank you.

**Comment by BeemerDream** [comment]
I moved it to the desktop, then it worked 👍
