### ISSUE TITLE
Multiple client_id´s

### ISSUE THREAD

**Issue by BeemerDream** [zorua98741/PS3-Rich-Presence-for-Discord#23]
Hi again!

I noticed that sometimes it will say Retro instead of XMB
Sorry if I´m creating this as an issue, but I tried to message on DC.

Thanks in advance.

**Comment by zorua98741** [comment]
Hi, I don't seem to have any messages on Discord?
As for the issue title, multiple client_id aren't supported yet, it is in progress for when PS3 and PS4 versions of the script are either merged or made to use the same functions for maintainability.
For it saying "retro" while in XMB, this will happen whenever you have a PS2 or PS1 game mounted, maybe also PSP?
