### ISSUE TITLE
Manually adding game names

### ISSUE THREAD

**Issue by ngoomie** [zorua98741/PS3-Rich-Presence-for-Discord#4]
Hello! I've been looking for some way to have my PS3 game activity show up on my profile and this is exactly what I've been looking for, but as is mentioned in the README, grabbing images for games with Japanese characters or the like in their name doesn't really work. Most of the games I play are Japanese so I tried to figure out how to add games manually on my own — even though you offer to help with adding games to the script itself I didn't want to bother you when it wasn't necessary so I figured it was worth a shot. Seems what I thought would work isn't quite it though, I had assumed changing any Japanese games to have a separate application from the rest in the `# INDIVIDUAL GAME CODE HERE` section would fix it. I'd very much appreciate any help you could offer!

**Comment by zorua98741** [comment]
Hi, the current version of PS3RPD is outdated, and i am currently working on writing out an improved version where adding images is much easier.
please note that manually adding games to the .py script is only to display separate __names__ and will not work to add an image
In the meantime however, you can send me the output of the ```validate():``` function when you have one of the games open, and i will upload the image to my Discord Developer Application

**Comment by ngoomie** [comment]
Thanks for the response! Honestly, I'm fine using my own developer application in the meantime. I wish you luck with the rewrite! :)

**Comment by xfrcc** [comment]
afaik doesn't webman mod provides game title id? it think that's better

**Comment by zorua98741** [comment]
Hi, if possible, could you please send through the name of some games you have had issues with? I think I have a workaround for this issue, but would like to give it a few more test cases
