### ISSUE TITLE
Python script fails when I start a PS3 game

### ISSUE THREAD

**Issue by ShadowOfPripyat** [zorua98741/PS3-Rich-Presence-for-Discord#5]
Everything was fine when I was in the XMB menu, but when I tried to start **GTA IV** and **Gran Turismo 6** , the rich presence stopped working with these errors: 
![image](https://user-images.githubusercontent.com/73404930/187676110-15161a2f-d108-4e56-b5ea-62aa808ee582.png)
(I used Python 3.9 On a Ubuntu 20.04 Terminal), with WebMan mod installed on my Fat PS3.

**Comment by zorua98741** [comment]
Hello! The script has had extremely little testing on anything other than Windows 10, when I get a moment I'll give it a go on Ubuntu and see what I can find

**Comment by zorua98741** [comment]
I've been able to get the .py script working on a virtual machine with the following specifications:
- Ubuntu 20.04.5 LTS
- WebmanMOD 1.47.41 & 1.47.42
- Gran Turismo 6 (BCUS98296)
- Python 3.8.10 & Python 3.9.14
