### ISSUE TITLE
Workaround for adding images to games with foreign characters?

### ISSUE THREAD

**Issue by SK91no** [zorua98741/PS3-Rich-Presence-for-Discord#7]
This is more of a Discord problem but I tried to run Misato Katsuragi's Reporting Plan (葛城ミサト報道計画_0100)
The Discord portal cannot save the kanji citing the image
![image](https://user-images.githubusercontent.com/63129189/196060981-8f0b087c-f6f3-4d4b-a055-3eb798a94986.png)
If we could customize the ID for instance while internally keeping it the same that would be cool.

**Comment by zorua98741** [comment]
If this is a PS3 game you should be able to set the name of the game as the titleID

**Comment by SK91no** [comment]
NVM I feel like an idiot, this exact issue has already been a focal point in the closed issues.
